# --- UPDeT parameters ---
# Switch between QMIX and VDN by changing the "mixer" parameter below.

action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000
evaluation_epsilon: 0.0

runner: "episode"

# Buffer
buffer_size: 5000
prioritized_buffer: False
prioritized_buffer_alpha: 0.6

target_update_interval_or_tau: 200

obs_agent_id: False         # It should be False
obs_last_action: False      # It should be False
obs_individual_obs: False   # It should be False

standardise_returns: False
standardise_rewards: True

agent_output_type: "q"
learner: "q_learner"
double_q: True
mixer: "qmix"    # change to "vdn" to use VDN instead
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

# Agent
agent: "updet"
mac: "updet_mac"

# Transformer hyperparameters
emb: 32
heads: 4
depth: 2

name: "updet"
