# --- HAPPO specific parameters ---

action_selector: "soft_policies"
mask_before_softmax: True

runner: "parallel"

buffer_size: 10
batch_size_run: 10
batch_size: 10
num_mini_batch: 1

lr: 0.0005

obs_agent_id: False
obs_last_action: False
obs_individual_obs: False

mac: "basic_mac"
agent: "rnn"
agent_output_type: "pi_logits"
learner: "happo_learner"
entropy_coef: 0.01
use_rnn: False
standardise_returns: False
standardise_rewards: False
standardise_advantages: True
q_nstep: 5 # 1 corresponds to normal r + gammaV
critic_type: "cv_critic"
epochs: 4
eps_clip: 0.2
name: "happo"
huber_delta: 10.0

t_max: 20050000
