# --- MASER specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000
evaluation_epsilon: 0.0

runner: "episode"
batch_size_run: 1

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "maser_q_learner"
double_q: True
mixer: "qmix"
use_rnn: True
mixing_embed_dim: 32
lam: 0.03
alpha: 0.5
ind: 0.8
mix: 0.2
expl: 0.3
dis: 0.7
goal: "jjw_dqn_update"
name: "maser"
timestep: "2000051"

latent_dim: 3
NN_HIDDEN_SIZE: 16
var_floor: 0.002