# --- MAPPO specific parameters ---

action_selector: "multinomial"
mask_before_softmax: True                           # same as mappo (CR_18jul2024)

runner: "episode"

buffer_size: 2 # 10                                 # same as mappo (CR_18jul2024)
batch_size_run: 2 # 10                              # same as mappo (CR_18jul2024)
batch_size: 2 # 10                                  # same as mappo (CR_18jul2024)

# update the target network every {} training steps
target_update_interval_or_tau: 200                  # same as mappo (CR_18jul2024)

lr: 0.0005                                          # same as mappo (CR_18jul2024)

obs_agent_id: True                                  # same as mappo (CR_18jul2024)?
obs_last_action: True                               # same as mappo (CR_18jul2024)?
obs_individual_obs: False                           # same as mappo (CR_18jul2024)?

agent_output_type: "pi_logits"                      # same as mappo (CR_18jul2024)?
learner: "mat_learner"
entropy_coef: 0.01                                  # same as mappo (CR_18jul2024)?
use_rnn: True                                       # same as mappo (CR_18jul2024)?
standardise_returns: False                          # same as mappo (CR_18jul2024)?
standardise_rewards: True                           # same as mappo (CR_18jul2024)?
q_nstep: 5 # 1 corresponds to normal r + gammaV     # same as mappo (CR_18jul2024)
critic_type: "cv_critic"                            # same as mappo (CR_18jul2024)?
epochs: 4                                           # same as mappo (CR_18jul2024)?
eps_clip: 0.2                                       # same as mappo (CR_18jul2024)
name: "mat"

t_max: 5050000 # 20050000                           # same as mappo (CR_18jul2024)
