env: "capture_target"

env_args:
  key: CaptureTarget-v0
  seed: null
  n_target: 1
  n_agent: 2
  grid_dim: [6,6] # grid world size
  terminate_step: 60 # Maximal steps for termination
  obs_one_hot: False # Whether represents observation as one-hot vector
  intermediate_r: False
  target_flick_prob: 0.3 # Probability of not observing the target
  tgt_avoid_agent: True
  tgt_trans_noise: 0.0
  agent_trans_noise: 0.1 # Agent dynamics noise in Capture Target domain

test_greedy: True
test_nepisode: 100
test_interval: 500
log_interval: 500
runner_log_interval: 250
learner_log_interval: 250
t_max: 10000

# Capture Target
# RUN: python3 src/main.py --config=qmix --env-config=capture_target with env_args.terminate_step=60