env: "capturetarget"

env_args:
  key: null # Options: CaptureTarget-6x6-1t-2a-v0
  seed: null
  terminate_step: 60 # Maximal steps for termination
  obs_one_hot: False # Whether represents observation as one-hot vector
  intermediate_r: False
  target_flick_prob: 0.3 # Probability of not observing the target
  tgt_avoid_agent: True
  tgt_trans_noise: 0.0
  agent_trans_noise: 0.1 # Agent dynamics noise in Capture Target domain

test_greedy: True
test_nepisode: 100
test_interval: 500 # 50000
log_interval: 500 # 50000
runner_log_interval: 250 # 10000
learner_log_interval: 250 # 10000
t_max: 10000 # # 20050000

# Capture Target
# RUN: python3 src/main.py --config=qmix --env-config=capturetarget with env_args.key="CaptureTarget-6x6-1t-2a-v0" env_args.terminate_step=60