env: "gymma"

env_args:
  key: null
  time_limit: 100

test_greedy: True
test_nepisode: 100
test_interval: 500 # 50000
log_interval: 500 # 50000
runner_log_interval: 250 # 10000
learner_log_interval: 250 # 10000
t_max: 10000 # 2050000

# RWARE
# RUN: python3 src/main.py --config=qmix --env-config=gymma with env_args.time_limit=500 env_args.key="rware:rware-tiny-2ag-v1"

# LBF:
# RUN: python3 src/main.py --config=qmix --env-config=gymma with env_args.time_limit=25 env_args.key="lbforaging:Foraging-8x8-2p-3f-v2" # NOTE: v2 not v1

# MPE
# RUN: python3 src/main.py --config=qmix --env-config=gymma with env_args.time_limit=25 env_args.key="mpe:SimpleSpeakerListener-v0"
