env: "pettingzoo"

env_args:
  key: null
  max_cycles: null
  render_mode: "rgb_array" # Options: "human", "rgb_array
  trainable_cnn: False # When this is True, image encoder parameters do not matter.
  image_encoder: "ResNet18" # Options: "ResNet18", "SlimSAM", "CLIP"
  image_encoder_batch_size: 1
  image_encoder_use_cuda: True
  kwargs: "" # Use in terminal: env_args.kwargs="('arg1',arg1_value), ('arg2',arg2_value)"

test_greedy: True
test_nepisode: 10 # 100
test_interval: 500 # 50000
log_interval: 500 # 50000
runner_log_interval: 1000 # 10000
learner_log_interval: 1000 # 10000
t_max: 2000 # 2050000

# Pistonball
# https://pettingzoo.farama.org/environments/butterfly/pistonball/
# args: max_cycles=125, render_mode="human", n_pistons=20, time_penalty=-0.1, continuous=True, random_drop=True, random_rotate=True, ball_mass=0.75, ball_friction=0.3, ball_elasticity=1.5
# RUN:  python3 src/main.py --config=qmix --env-config=pettingzoo with env_args.key="pistonball_v6" env_args.kwargs="('n_pistons',4),"

# Cooperative Pong
# https://pettingzoo.farama.org/environments/butterfly/cooperative_pong/
# args: max_cycles=900, render_mode="human", ball_speed=9, left_paddle_speed=12, right_paddle_speed=12, cake_paddle=True, max_cycles=900, bounce_randomness=False, max_reward=100, off_screen_penalty=-10
# RUN: python3 src/main.py --config=qmix --env-config=pettingzoo with env_args.key="cooperative_pong_v5"

# All (the following) atari games have these default args: obs_type='rgb_image', full_action_space=True, max_cycles=100000, auto_rom_install_path=None)
# Entombed Cooperative
# https://pettingzoo.farama.org/environments/atari/entombed_cooperative/
# RUN: python3 src/main.py --config=qmix --env-config=pettingzoo with env_args.max_cycles=2500 env_args.key="entombed_cooperative_v3"

# Space Invaders
# https://pettingzoo.farama.org/environments/atari/space_invaders/
# args: alternating_control=False, moving_shields=True, zigzaging_bombs=False, fast_bomb=False, invisible_invaders=False
# RUN: python3 src/main.py --config=qmix --env-config=pettingzoo with env_args.max_cycles=2500 env_args.key="space_invaders_v2"