name: Publish Package to PyPI

on:
  release:
    types: [created]

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.18'

      - name: Upgrade pip and install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine setuptools_scm

      - name: Build package
        run: python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/


      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: AILabDsUnipi
          TWINE_PASSWORD: "${{ secrets.PYPI_API_TOKEN }}"
        run: twine upload dist/* --verbose


